services:
  - type: web
    name: ai-chat
    env: static
    buildCommand: ./render-build.sh
    staticPublishPath: ./
    envVars:
      - key: API_KEY
        sync: false
      - key: ENDPOINT
        sync: false
      - key: DEPLOYMENT_NAME
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
