services:
  - type: web
    name: aichat
    runtime: static
    buildCommand: null
    staticPublishPath: ./
    envVars:
      - key: API_KEY
        value: YOUR_API_KEY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
