services:
  - type: web
    name: aichat
    env: static
    buildCommand: ./render-build.sh
    staticPublishPath: ./
    envVars:
      - key: OPENAI_API_KEY
        sync: false # يجب إدخال القيمة يدويًا في لوحة تحكم Render
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
